[profile.default]

# Dont let multiple tests stuck on downloading model
[[profile.default.overrides]]
filter = 'package(ferrex-core) & kind(test)'
test-group = 'serial-integration'

[[profile.default.overrides]]
filter = 'package(ferrex-server) & kind(test)'
test-group = 'serial-integration'

[test-groups.serial-integration]
max-threads = 1

[profile.ci]
